###
POST localhost:8071/update/1/1234

###
POST localhost:8071/update/2/284

###

POST localhost:8071/createacc/2

###
GET localhost:8070/cashback/1

###

POST localhost:8070/getcashback/1

###
POST localhost:8071/update/3/4564

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 1000
}

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 2,
  "destinationId": 1,
  "value": 2347
}